### PR TITLE
Ensure to use TimeSpan type when searching for the timespan log overloads

### LINKED ISSUE #66: Incorrect parameters when detecting log methods?
See https://github.com/Fody/MethodTimer/blob/master/MethodTimer.Fody/InterceptorFinder.cs#L94

I would expect TimeSpan instead of Long there?

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
Fixes #66

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
I guess. I could write a few if you want.

**Comment by GeertvanHorrik** [comment]
Note that this is a bit of a complex scenario that only occurs when you don't create a custom `MethodTimeLogger` per project, but need to reference it from a referenced project.

**Comment by GeertvanHorrik** [comment]
(so there are unit tests for the timespan overload, just not for this single scenario)

**Comment by SimonCropp** [comment]
Yeah don’t sweat the tests. I will add some unit tests this weekend. 

U happy for me to merge and deploy this as is?

**Comment by GeertvanHorrik** [comment]
And now I think about this, this might actually be the bug of #65 , because it thinks it has a timespan overload, and it passes in the TimeSpan as long :)

2 birds with 1 stone!

**Comment by GeertvanHorrik** [comment]
Yes, I also made an optimization commit to master, but this can be merged.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Pull request merged**
