### PR TITLE
Simplify async method handling and fix some bugs

### LINKED ISSUE #124: Async method that throws Exception not working
#### You should already be a Patron

I am testing Fody to see if we can use it in our project and if so, we will become a patron. If this means that I cannot raise an issue, please ignore this.

#### Describe the issue

I have a simple async function that awaits a Task and then throws an exception afterwards. When I wrap this with [Time] there are two things that go weird a) the total time is incorrect (the await time is not taken into account) b) the time is written to the console twice.

#### Minimal Repro

https://github.com/adrianignat13/MethodTimerSample

From output:
Program.AsyncDelay 12ms
Exception thrown: 'System.Exception' in MethodTimerSample.exe
Program.AsyncDelay 12ms

Expected output (manual weaving)
Program.AsyncDelayWithTimer 00:00:01.0291857ms
Exception thrown: 'System.AggregateException' in mscorlib.dll

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
#### Description

Fixes #124 

#### The solution

The reason it was not working correctly is because of the throwing of the exception that caused no other exit paths available in the example method.

I've much simplified the way MethodTimer deals with async methods by changing the following:

1. Add member method that only logs when the state machine is complete (state value == -2)
2. Call this method after every MoveNext call at the end of the method *or* before SetException (then the method execution stops as well)

Here is the output of a test console app:

image

The bottom one is from the repro provided by @adrianignat13 

Here is the updated generated code after weaving for a state machine:

**StopMethodTimerStopwatch()**

```
private void StopMethodTimerStopwatch()
{
    if (this.<>__state != -2)
        return;
    this.methodTimerStopwatch.Stop();
    this.methodTimerMessage = (string) null;
    MethodTimeLogger.Log(MethodBase.GetMethodFromHandle(__methodref (Program.AsyncDelay), __typeref (Program)), this.methodTimerStopwatch.ElapsedMilliseconds, this.    
}
```

**MoveNext()**

As you can see, there are 2 places where `StopMethodTimerStopwatch` is being called, just before `SetException` and at the end of the method)

```
void IAsyncStateMachine.MoveNext()
{
    if (this.methodTimerStopwatch == null)
        this.methodTimerStopwatch = Stopwatch.StartNew();
    int num1 = this.<>1__state;
    try
    {
      TaskAwaiter awaiter;
      int num2;
      if (num1 != 0)
      {
        awaiter = Task.Delay(1000).GetAwaiter();
        if (!awaiter.IsCompleted)
        {
            this.<>1__state = num2 = 0;
            this.<>u__1 = awaiter;
            Program.<AsyncDelay>d__7 stateMachine = this;
            this.<>t__builder.AwaitUnsafeOnCompleted<TaskAwaiter, Program.<AsyncDelay>d__7>(ref awaiter, ref stateMachine);
            goto label_9;
        }
      }
      else
      {
        awaiter = this.<>u__1;
        this.<>u__1 = new TaskAwaiter();
        this.<>1__state = num2 = -1;
      }
      awaiter.GetResult();
      throw new Exception();
    }
    catch (Exception ex)
    {
        this.<>1__state = -2;
        ref AsyncTaskMethodBuilder local = ref this.<>t__builder;
        Exception exception = ex;
        this.StopMethodTimerStopwatch();
        local.SetException(exception);
    }
    label_9:
    this.StopMethodTimerStopwatch();
}
```

### CODE REVIEW

**Comment by SimonCropp** [comment]
seems to be failing CI

**Comment by GeertvanHorrik** [comment]
Just fixed, had some issues with running the tests in release mode in VS, but finally got it to work.

**Comment by SimonCropp** [comment]
@GeertvanHorrik thanks for the awesome work.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Pull request merged**
