### PR TITLE
Add support for parameters formatting

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
This is a WIP. Will inform you whenever this is ready.

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
This PR is ready for review. This is a non-breaking change. Users that want to use this new feature will have to update their interceptor method signature to this:

```
public static void Log(MethodBase methodBase, long milliseconds, string message)
```

Whenever there is an attribute *without* a formatting, the message will be *null*. The reasoning behind this is that a user *could* use an empty string as formatting as well (or the string.Format result could result in an empty string).

1. Usage is simple. Add an attribute like this. The generated code will do a string.Format (with boxing etc taken care of) on the parameter + the formatting string. This functionality is covered by the unit tests.

```
[Time("This is magic! {parameter1} & {parameter2}")]
public void MyMethod(string parameter1, int parameter2)
{

}
```

2. If this new feature is used, the user *must* specify a new overload. However, if they don't use this feature, this is not a breaking change. The weaver will log an error explaining the user what to do. This functionality is covered by the unit tests.

3. If a parameter is being used that is not available (e.g. a typo), the weaver will log an error asking the user to fix. This functionality is covered by the unit tests.

If you want something changed, please let me know.

**Comment by GeertvanHorrik** [comment]
4. For async methods, the compiler will optimize (exclude) unused parameters in the state machine. Whenever an optimized parameter is being used in the formatting, the weaver will now log an error. This functionality is covered by the unit tests.

**Comment by SimonCropp** [comment]
Any objections to me making u a maintainer of this project?

**Comment by GeertvanHorrik** [comment]
No, please do, makes stuff easier.

**Comment by SimonCropp** [comment]
done

**Comment by GeertvanHorrik** [comment]
Thanks. I am now part of the team, but cannot assign this PR nor can I merge it. Did you add rights to the team in GH as well?

**Comment by SimonCropp** [comment]
sorry only added read. changed to admin, try now

**Comment by GeertvanHorrik** [comment]
Works now, thanks. You want to review this one or do you just want me to merge it?

**Comment by SimonCropp** [comment]
dont have time to review today. would be able to tomorrow. but i dont NEED to :)

will leave it up to you

**Comment by GeertvanHorrik** [comment]
It's all covered by unit tests.

**Comment by mtumashenko** [comment]
@GeertvanHorrik Is there a possibility to allow parameter's public property to be used in Time attribute? For example:
`[Time("This is magic! {parameter1.Property1} & {parameter2.Property2}")]`

**Comment by GeertvanHorrik** [comment]
At this stage it's not possible, but I think that's doable. The thing is: do you want this to potentially affect the performance at run-time (we don't know the implementation of the property getter).

**Pull request merged**
