### PR TITLE
Improved async handling

### LINKED ISSUE #20: NullReferenceException on stopwatch
image

This happens on an async method that is nested. Going to check if I can reproduce. This code has always worked, just updated to latest version of MethodTimer and it fails now.

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
Fixes #20

1) Stop the stopwatch when an exception occurs (bug fix)
2) Instead of using the first TryCatch, instantiate the stopwatch at the beginning of the method (if != null). This fixes a possible NullReferenceException in fast-path optimized methods

### CODE REVIEW

**Comment by SimonCropp** [comment]
getting 

```
[IL]: Error: [C:\Code\MethodTimer\AssemblyWithoutInterceptor\bin\Release\AssemblyWithoutInterceptor2.dll : ClassWithAsyncMethod+<MethodWithEmptyAsync>d__0::MoveNext][offset 0x00000009][found Int32][expected ref 'System.Exception'] Unexpected type on the stack.
1 Error(s) Verifying C:/Code/MethodTimer/AssemblyWithoutInterceptor/bin/Release/AssemblyWithoutInterceptor2.dll
```

any ideas ?

**Comment by GeertvanHorrik** [comment]
Maybe I screwed up custom try / catch statements inside an async method. But does this occur on the current unit tests?

**Comment by GeertvanHorrik** [comment]
Sometimes restarting vs helps.

**Comment by SimonCropp** [comment]
yep. but only in release mode

**Comment by GeertvanHorrik** [comment]
Let me investigate.

**Comment by GeertvanHorrik** [comment]
Compared IL looks good to me (with a non-weaved empty async method), investigating if this only happens to empty async methods.

**Comment by GeertvanHorrik** [comment]
The if(_stopwatch == null) check is the culprit.

**Comment by GeertvanHorrik** [comment]
Forgot to define a variable for the boolean check, sorry for the inconvenience. Should be fixed.

**Comment by SimonCropp** [comment]
yep all good after that last PR. pushed to nuget

**Comment by GeertvanHorrik** [comment]
Thanks for the fast responses. Much appreciated.

**Comment by SimonCropp** [comment]
no worries. thanks for the PR

**Pull request merged**
